spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: sa
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: always
  jmx:
    enabled: true
  data:
    mongodb:
      database: microservices
      uri: mongodb://localhost:27017
  application:
    name: spring-cloud-eureka-client

password:
  length: 10
  strength: 12
  pepper: "5f7j2k"

server:
  hostname: "localhost"
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: http://localhost:8080, http://localhost:8081
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

security:
  jwt:
    signing-key: "0dbe9fb91dcd"
    access-token:
      expires-in-s: 172800 #60*60*48

eureka:
  instance:
    hostname: localhost

hystrix:
  command:
    getAll:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#logging:
#  level:
#    root: debug