spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: sa
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: always
  jmx:
    enabled: true
  data:
    mongodb:
      database: microservices
      uri: mongodb://localhost:27017
  application:
    name: spring-cloud-eureka-client

password:
  length: 10
  strength: 12
  pepper: "5f7j2k"

server:
  hostname: "localhost"
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: http://localhost:8080, http://localhost:8081
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

security:
  jwt:
    signing-key: "MIIEogIBAAKCAQEAkVvRct+JLtWE7KomD7wYEMMHvUm8jFcH38JtJR9x2+SgSdSe1iHkFPD0sT0YaW46obJ+7eu+GiRZyB/pi9XaKlmh2IwGg+mZqd9FYh5Nb88VHnNqg5SZ8pOsHx6bZqRfOFWrgXL0OD++ss/RWEdThx/PrfYlAz9a8QPJ22QT8TPb0Pc39SP2bNhYnDGz05O76tm5/JCApDp0zSvGapi86rMRrq17O6lcXWGUHHqJoqC98k3xPb9nZtcS6ur5pmxYiPd704U41H5wM5jPoYEC+1b3ISofY9OFTznDQLw5Mg9II0v4MQUg32nMHLWMURfMWdKdVagYZVSw0dAFww0C0QIDAQABAoIBAHoh1L0ZNvGD8/jKCcrktq+2vtT7lJGyOmp2uTAc2JTy5v7ByGeQ+EvkHSSiedV0CY19JYsQrZzXeBxfO+MDXxiAUS1akcraRwNlFq4XWecc7ti0DwXZoPQhwdgv5lB6wYra6IyOosZ0QO2LEZGD9JmvT9cR3w14eRfSoBNXZi4dn90wA4XbvWdPI+6oFR/4iFMzz2hrWPSygskWXlzB9kXtNvLwTO2F4zwVXoiUHImChfEuDXxC8wPjxFLjfLNyuByAOdNo8PYrHcJT4PfmpLqcSgODPTZBTqtokcnHk5MS0hOonyIfI7vIROHN9LHtYtQlRJV5O9G/zVvnWJW5BkECgYEA9bIQ4b5vqS1mpPRwzX5amwr8qHVt7VN6fdzPZsqGXJqeFmffDNDilojE1vOxjbA7vEA4VvTaUC605M5tfzGTanSLK7ikzCLpty3mksw43OxsPudYgN3cBVqpvpMETDfzVkLqRzuWUnrYNZbLf3EHbzPE+tJPhaCiBnpcdhMEDKkCgYEAl3R5tChcWrwIEv+8muNKWz6Z7b45CbU8p5FJekqpnUa+kMjius1EeGVj5F/SfH1/n/9JW4MFG4B1tpmIKx20ICFkcykYM8GYuKTD5LKLwcNbEzMMcxlPuHdCnrWWbXlHCBLPryIBtSYb0w2sBTRxnlXNn4/nZ52uIJ6WgYRatekCgYADDi7Vj9e1o+Hl5UBN3edkjDNuKN+wFtysGgXeQmB/YFDc+He2ohZfRt4jyi4IFAv6IFZTBoJ8gsgvHD4SWdx6c26ToZ0zCLAdXg3C/5Upcis6cQgRujCVRHZd71gbVorJJNXjAuOwrORpbjGjqRUtldg6QklI4SGCsRzbPwtK2QKBgCMnApRhBcZ9e/ZE6xacCIcTCZEXpI9vREu0OfSrXaDGababGZy3xduX1M6NuwHv8u5Ex1b5GvdeInQmQGeZdlQ6y+C6ugZROcwpWdo74povaHUVVR9l0Y4ECC9kAC0ah/UEwLVqVDEiTjT3KGTw3iocyiPtt4ziGSczB8W53X/5AoGAfVVQEJhvzXe8XAXsex3Ze5CFmyAebMbD0WFa1Ge+iRtajossVcbPl1RRLtJEaEJogDd3uRqVPRLHWa8beiqiLNImlr9rfFqAFmf9UgiEgZswdlAKr5OXS92uf3yGhH+kjs7vXAIhZemwsw5qEadoYuH5SOgXWEs9j4UP7xtLz9w="
    public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkVvRct+JLtWE7KomD7wYEMMHvUm8jFcH38JtJR9x2+SgSdSe1iHkFPD0sT0YaW46obJ+7eu+GiRZyB/pi9XaKlmh2IwGg+mZqd9FYh5Nb88VHnNqg5SZ8pOsHx6bZqRfOFWrgXL0OD++ss/RWEdThx/PrfYlAz9a8QPJ22QT8TPb0Pc39SP2bNhYnDGz05O76tm5/JCApDp0zSvGapi86rMRrq17O6lcXWGUHHqJoqC98k3xPb9nZtcS6ur5pmxYiPd704U41H5wM5jPoYEC+1b3ISofY9OFTznDQLw5Mg9II0v4MQUg32nMHLWMURfMWdKdVagYZVSw0dAFww0C0QIDAQAB"
    access-token:
      expires-in-s: 172800 #60*60*48

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    ip-address: localhost
#    hostname: localhost

hystrix:
  command:
    getAll:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#logging:
#  level:
#    root: debug